export const API_ENDPOINTS = {
  HEALTH: "/health",
  AUTH: {
    SIGNUP: "/auth/signup",
    TOKEN: "/auth/token",
    REFRESH_TOKEN: "/auth/token/refresh",
    PASSWORD_RESET: {
      REQUEST: "/auth/password-reset/request",
      CONFIRM: "/auth/password-reset/confirm",
    },
    GOOGLE: {
      INDEX: "/auth/google",
      START: "/auth/google/start",
      CALLBACK: "/auth/google/callback",
    },
    USER: "/auth/user",
    STATUS: "/auth/status",
    LOGOUT: "/auth/logout",
  },
  PROFILES: {
    ME: "/profiles/me",
  },
  STORAGE: {
    GET: (bucket: string, path: string) => `/storage/${bucket}/${path}`,
    UPLOAD: (bucket: string) => `/storage/${bucket}/upload`,
    SIGN_PUT: "/storage/uploads/sign-put",
    SIGN_MULTIPART: "/storage/uploads/sign-multipart",
  },
  PUBLIC: {
    SERVICES: {
      LIST: "/services",
      DETAIL: (id: string) => `/services/${id}`,
      BY_SLUG: (slug: string) => `/services/by-slug/${slug}`,
      IMAGES: (id: string) => `/services/${id}/images`,
    },
    PRODUCTS: {
      LIST: "/products",
      DETAIL: (idOrSlug: string) => `/products/${idOrSlug}`,
      BY_SLUG: (slug: string) => `/products/by-slug/${slug}`,
      BY_ID: (id: string) => `/products/id/${id}`,
      FAQS: "/product_faqs",
      SPECS: "/product_specs",
      REVIEWS: "/product_reviews",
    },
    REFERENCES: {
      LIST: "/references",
      DETAIL: (id: string) => `/references/${id}`,
      BY_SLUG: (slug: string) => `/references/by-slug/${slug}`,
    },
    CATEGORIES: {
      LIST: "/categories",
      DETAIL: (id: string) => `/categories/${id}`,
      BY_SLUG: (slug: string) => `/categories/by-slug/${slug}`,
    },
    SUB_CATEGORIES: {
      LIST: "/sub-categories",
      DETAIL: (id: string) => `/sub-categories/${id}`,
      BY_SLUG: (slug: string) => `/sub-categories/by-slug/${slug}`,
    },
    MENU_ITEMS: {
      LIST: "/menu_items",
      DETAIL: (id: string) => `/menu_items/${id}`,
    },
    SLIDERS: {
      LIST: "/sliders",
      DETAIL: (idOrSlug: string) => `/sliders/${idOrSlug}`,
    },
    CONTACTS: "/contacts",
    FAQS: {
      LIST: "/faqs",
      DETAIL: (id: string) => `/faqs/${id}`,
      BY_SLUG: (slug: string) => `/faqs/by-slug/${slug}`,
    },
    CUSTOM_PAGES: {
      LIST: "/custom_pages",
      DETAIL: (id: string) => `/custom_pages/${id}`,
      BY_SLUG: (slug: string) => `/custom_pages/by-slug/${slug}`,
    },
    FOOTER_SECTIONS: {
      LIST: "/footer_sections",
      DETAIL: (id: string) => `/footer_sections/${id}`,
      BY_SLUG: (slug: string) => `/footer_sections/by-slug/${slug}`,
    },
    LIBRARY: {
      LIST: "/library",
      DETAIL: (id: string) => `/library/${id}`,
      BY_SLUG: (slug: string) => `/library/by-slug/${slug}`,
      IMAGES: (id: string) => `/library/${id}/images`,
      FILES: (id: string) => `/library/${id}/files`,
    },
    REVIEWS: {
      LIST: "/reviews",
      DETAIL: (id: string) => `/reviews/${id}`,
      REACTIONS: (id: string) => `/reviews/${id}/reactions`,
    },
    SUPPORT_TICKETS: {
      LIST: "/support_tickets",
      DETAIL: (id: string) => `/support_tickets/${id}`,
    },
    TICKET_REPLIES: {
      LIST: "/ticket_replies",
      BY_TICKET: (ticketId: string) => `/ticket_replies/by-ticket/${ticketId}`,
    },
    OFFERS: "/offers",
    CATALOG_REQUESTS: "/catalog-requests",
    SITE_SETTINGS: {
      LIST: "/site_settings",
      BY_KEY: (key: string) => `/site_settings/${key}`,
      APP_LOCALES: "/site_settings/app-locales",
      DEFAULT_LOCALE: "/site_settings/default-locale",
    },
    NEWSLETTER: {
      SUBSCRIBE: "/newsletter/subscribe",
      UNSUBSCRIBE: "/newsletter/unsubscribe",
    },
    NOTIFICATIONS: {
      LIST: "/notifications",
      UNREAD_COUNT: "/notifications/unread-count",
      DETAIL: (id: string) => `/notifications/${id}`,
      MARK_ALL_READ: "/notifications/mark-all-read",
    },
  },
  ADMIN: {
    DASHBOARD: {
      SUMMARY: "/admin/dashboard/summary",
    },
    AUDIT: {
      REQUEST_LOGS: "/admin/audit/request-logs",
      AUTH_EVENTS: "/admin/audit/auth-events",
      METRICS_DAILY: "/admin/audit/metrics/daily",
      STREAM: "/admin/audit/stream",
    },
    USERS: {
      LIST: "/admin/users",
      DETAIL: (id: string) => `/admin/users/${id}`,
      ACTIVE: (id: string) => `/admin/users/${id}/active`,
      ROLES: (id: string) => `/admin/users/${id}/roles`,
      PASSWORD: (id: string) => `/admin/users/${id}/password`,
    },
    CUSTOM_PAGES: {
      LIST: "/admin/custom_pages",
      DETAIL: (id: string) => `/admin/custom_pages/${id}`,
      BY_SLUG: (slug: string) => `/admin/custom_pages/by-slug/${slug}`,
      REORDER: "/admin/custom_pages/reorder",
    },
    SITE_SETTINGS: {
      LIST: "/admin/site-settings",
      BY_KEY: (key: string) => `/admin/site-settings/${key}`,
      BULK_UPSERT: "/admin/site-settings/bulk-upsert",
      APP_LOCALES: "/admin/site-settings/app-locales",
      DEFAULT_LOCALE: "/admin/site-settings/default-locale",
    },
    FAQS: {
      LIST: "/admin/faqs",
      DETAIL: (id: string) => `/admin/faqs/${id}`,
      BY_SLUG: (slug: string) => `/admin/faqs/by-slug/${slug}`,
    },
    SERVICES: {
      LIST: "/admin/services",
      DETAIL: (id: string) => `/admin/services/${id}`,
      BY_SLUG: (slug: string) => `/admin/services/by-slug/${slug}`,
      REORDER: "/admin/services/reorder",
      IMAGES: {
        LIST: (id: string) => `/admin/services/${id}/images`,
        DETAIL: (id: string, imageId: string) => `/admin/services/${id}/images/${imageId}`,
      },
    },
    REFERENCES: {
      LIST: "/admin/references",
      DETAIL: (id: string) => `/admin/references/${id}`,
      BY_SLUG: (slug: string) => `/admin/references/by-slug/${slug}`,
    },
    STORAGE: {
      ASSETS: {
        LIST: "/admin/storage/assets",
        DETAIL: (id: string) => `/admin/storage/assets/${id}`,
        BULK: "/admin/storage/assets/bulk",
        BULK_DELETE: "/admin/storage/assets/bulk-delete",
      },
      FOLDERS: "/admin/storage/folders",
      DIAG_CLOUD: "/admin/storage/_diag/cloud",
    },
    MENU_ITEMS: {
      LIST: "/admin/menu_items",
      DETAIL: (id: string) => `/admin/menu_items/${id}`,
      REORDER: "/admin/menu_items/reorder",
    },
    SLIDERS: {
      LIST: "/admin/sliders",
      DETAIL: (id: string) => `/admin/sliders/${id}`,
      REORDER: "/admin/sliders/reorder",
      STATUS: (id: string) => `/admin/sliders/${id}/status`,
      IMAGE: (id: string) => `/admin/sliders/${id}/image`,
    },
    CATEGORIES: {
      LIST: "/admin/categories/list",
      BASE: "/admin/categories",
      DETAIL: (id: string) => `/admin/categories/${id}`,
      BY_SLUG: (slug: string) => `/admin/categories/by-slug/${slug}`,
      REORDER: "/admin/categories/reorder",
      ACTIVE: (id: string) => `/admin/categories/${id}/active`,
      FEATURED: (id: string) => `/admin/categories/${id}/featured`,
      IMAGE: (id: string) => `/admin/categories/${id}/image`,
    },
    SUB_CATEGORIES: {
      LIST: "/admin/sub-categories/list",
      BASE: "/admin/sub-categories",
      DETAIL: (id: string) => `/admin/sub-categories/${id}`,
      BY_SLUG: (slug: string) => `/admin/sub-categories/by-slug/${slug}`,
      REORDER: "/admin/sub-categories/reorder",
      ACTIVE: (id: string) => `/admin/sub-categories/${id}/active`,
      FEATURED: (id: string) => `/admin/sub-categories/${id}/featured`,
      IMAGE: (id: string) => `/admin/sub-categories/${id}/image`,
    },
    CONTACTS: {
      LIST: "/admin/contacts",
      DETAIL: (id: string) => `/admin/contacts/${id}`,
    },
    DB: {
      EXPORT: "/admin/db/export",
      IMPORT_SQL: "/admin/db/import-sql",
      IMPORT_URL: "/admin/db/import-url",
      IMPORT_FILE: "/admin/db/import-file",
      EXPORT_MODULE: "/admin/db/export-module",
      IMPORT_MODULE: "/admin/db/import-module",
      SITE_SETTINGS_UI_EXPORT: "/admin/db/site-settings/ui-export",
      SITE_SETTINGS_UI_BOOTSTRAP: "/admin/db/site-settings/ui-bootstrap",
      MODULES_VALIDATE: "/admin/db/modules/validate",
      SNAPSHOTS: {
        LIST: "/admin/db/snapshots",
        RESTORE: (id: string) => `/admin/db/snapshots/${id}/restore`,
        DETAIL: (id: string) => `/admin/db/snapshots/${id}`,
      },
    },
    EMAIL_TEMPLATES: {
      LIST: "/admin/email_templates",
      DETAIL: (id: string) => `/admin/email_templates/${id}`,
    },
    FOOTER_SECTIONS: {
      LIST: "/admin/footer_sections",
      DETAIL: (id: string) => `/admin/footer_sections/${id}`,
      BY_SLUG: (slug: string) => `/admin/footer_sections/by-slug/${slug}`,
    },
    LIBRARY: {
      LIST: "/admin/library",
      DETAIL: (id: string) => `/admin/library/${id}`,
      BY_SLUG: (slug: string) => `/admin/library/by-slug/${slug}`,
      REORDER: "/admin/library/reorder",
      IMAGES: {
        LIST: (id: string) => `/admin/library/${id}/images`,
        DETAIL: (id: string, imageId: string) => `/admin/library/${id}/images/${imageId}`,
      },
      FILES: {
        LIST: (id: string) => `/admin/library/${id}/files`,
        DETAIL: (id: string, fileId: string) => `/admin/library/${id}/files/${fileId}`,
      },
    },
    NEWSLETTER: {
      LIST: "/admin/newsletter",
      DETAIL: (id: string) => `/admin/newsletter/${id}`,
    },
    PRODUCTS: {
      LIST: "/admin/products",
      DETAIL: (id: string) => `/admin/products/${id}`,
      IMAGES: {
        LIST: (id: string) => `/admin/products/${id}/images`,
        REPLACE: (id: string) => `/admin/products/${id}/images/replace`,
        DETAIL: (id: string, imageId: string) => `/admin/products/${id}/images/${imageId}`,
      },
      REORDER: "/admin/products/reorder",
      CATEGORIES: "/admin/products/categories",
      SUB_CATEGORIES: "/admin/products/subcategories",
      FAQS: {
        LIST: (id: string) => `/admin/products/${id}/faqs`,
        DETAIL: (id: string, faqId: string) => `/admin/products/${id}/faqs/${faqId}`,
        ACTIVE: (id: string, faqId: string) => `/admin/products/${id}/faqs/${faqId}/active`,
      },
      SPECS: {
        LIST: (id: string) => `/admin/products/${id}/specs`,
        DETAIL: (id: string, specId: string) => `/admin/products/${id}/specs/${specId}`,
      },
      REVIEWS: {
        LIST: (id: string) => `/admin/products/${id}/reviews`,
        DETAIL: (id: string, reviewId: string) => `/admin/products/${id}/reviews/${reviewId}`,
        ACTIVE: (id: string, reviewId: string) => `/admin/products/${id}/reviews/${reviewId}/active`,
      },
    },
    REVIEWS: {
      LIST: "/admin/reviews",
      DETAIL: (id: string) => `/admin/reviews/${id}`,
    },
    SUPPORT_TICKETS: {
      LIST: "/admin/support_tickets",
      DETAIL: (id: string) => `/admin/support_tickets/${id}`,
      ACTION: (id: string, action: string) => `/admin/support_tickets/${id}/${action}`,
    },
    TICKET_REPLIES: {
      LIST: "/admin/ticket_replies",
      BY_TICKET: (ticketId: string) => `/admin/ticket_replies/by-ticket/${ticketId}`,
      DETAIL: (id: string) => `/admin/ticket_replies/${id}`,
    },
    OFFERS: {
      LIST: "/admin/offers",
      DETAIL: (id: string) => `/admin/offers/${id}`,
      PDF: (id: string) => `/admin/offers/${id}/pdf`,
      EMAIL: (id: string) => `/admin/offers/${id}/email`,
      SEND: (id: string) => `/admin/offers/${id}/send`,
    },
    CATALOG_REQUESTS: {
      LIST: "/admin/catalog-requests",
      DETAIL: (id: string) => `/admin/catalog-requests/${id}`,
      RESEND: (id: string) => `/admin/catalog-requests/${id}/resend`,
    },
  },
};
